name: BUILDBOT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-64bit:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean previous builds
        run: |
          Remove-Item -Recurse -Force dist, build, __pycache__ -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyqt6 pycryptodome pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller build.spec
          
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: xv2tool_WIN64
          path: dist/

  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean previous builds
        run: |
          rm -rf dist build __pycache__

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyqt6 pycryptodome pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller build.spec

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: xv2tool_LINUX_x86_64
          path: dist/
